# Generated by Django 4.2.3 on 2023-08-04 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0003_remove_advertisement_created_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='update_date',
            new_name='updated_at',
        ),
    ]
